/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.apache.nifi.processor.email.extraction;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class EmailMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6756125773697839100L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EmailMessage\",\"namespace\":\"org.apache.nifi.processor.email.extraction\",\"fields\":[{\"name\":\"subject\",\"type\":\"string\"},{\"name\":\"body\",\"type\":\"string\"},{\"name\":\"body_type\",\"type\":{\"type\":\"enum\",\"name\":\"BodyType\",\"symbols\":[\"HTML\",\"PLAIN\",\"RTF\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<EmailMessage> ENCODER =
      new BinaryMessageEncoder<EmailMessage>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EmailMessage> DECODER =
      new BinaryMessageDecoder<EmailMessage>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<EmailMessage> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<EmailMessage> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<EmailMessage>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this EmailMessage to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a EmailMessage from a ByteBuffer. */
  public static EmailMessage fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence subject;
  @Deprecated public java.lang.CharSequence body;
  @Deprecated public org.apache.nifi.processor.email.extraction.BodyType body_type;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EmailMessage() {}

  /**
   * All-args constructor.
   * @param subject The new value for subject
   * @param body The new value for body
   * @param body_type The new value for body_type
   */
  public EmailMessage(java.lang.CharSequence subject, java.lang.CharSequence body, org.apache.nifi.processor.email.extraction.BodyType body_type) {
    this.subject = subject;
    this.body = body;
    this.body_type = body_type;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return subject;
    case 1: return body;
    case 2: return body_type;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: subject = (java.lang.CharSequence)value$; break;
    case 1: body = (java.lang.CharSequence)value$; break;
    case 2: body_type = (org.apache.nifi.processor.email.extraction.BodyType)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'subject' field.
   * @return The value of the 'subject' field.
   */
  public java.lang.CharSequence getSubject() {
    return subject;
  }

  /**
   * Sets the value of the 'subject' field.
   * @param value the value to set.
   */
  public void setSubject(java.lang.CharSequence value) {
    this.subject = value;
  }

  /**
   * Gets the value of the 'body' field.
   * @return The value of the 'body' field.
   */
  public java.lang.CharSequence getBody() {
    return body;
  }

  /**
   * Sets the value of the 'body' field.
   * @param value the value to set.
   */
  public void setBody(java.lang.CharSequence value) {
    this.body = value;
  }

  /**
   * Gets the value of the 'body_type' field.
   * @return The value of the 'body_type' field.
   */
  public org.apache.nifi.processor.email.extraction.BodyType getBodyType() {
    return body_type;
  }

  /**
   * Sets the value of the 'body_type' field.
   * @param value the value to set.
   */
  public void setBodyType(org.apache.nifi.processor.email.extraction.BodyType value) {
    this.body_type = value;
  }

  /**
   * Creates a new EmailMessage RecordBuilder.
   * @return A new EmailMessage RecordBuilder
   */
  public static org.apache.nifi.processor.email.extraction.EmailMessage.Builder newBuilder() {
    return new org.apache.nifi.processor.email.extraction.EmailMessage.Builder();
  }

  /**
   * Creates a new EmailMessage RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EmailMessage RecordBuilder
   */
  public static org.apache.nifi.processor.email.extraction.EmailMessage.Builder newBuilder(org.apache.nifi.processor.email.extraction.EmailMessage.Builder other) {
    return new org.apache.nifi.processor.email.extraction.EmailMessage.Builder(other);
  }

  /**
   * Creates a new EmailMessage RecordBuilder by copying an existing EmailMessage instance.
   * @param other The existing instance to copy.
   * @return A new EmailMessage RecordBuilder
   */
  public static org.apache.nifi.processor.email.extraction.EmailMessage.Builder newBuilder(org.apache.nifi.processor.email.extraction.EmailMessage other) {
    return new org.apache.nifi.processor.email.extraction.EmailMessage.Builder(other);
  }

  /**
   * RecordBuilder for EmailMessage instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EmailMessage>
    implements org.apache.avro.data.RecordBuilder<EmailMessage> {

    private java.lang.CharSequence subject;
    private java.lang.CharSequence body;
    private org.apache.nifi.processor.email.extraction.BodyType body_type;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.apache.nifi.processor.email.extraction.EmailMessage.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.subject)) {
        this.subject = data().deepCopy(fields()[0].schema(), other.subject);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.body)) {
        this.body = data().deepCopy(fields()[1].schema(), other.body);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.body_type)) {
        this.body_type = data().deepCopy(fields()[2].schema(), other.body_type);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing EmailMessage instance
     * @param other The existing instance to copy.
     */
    private Builder(org.apache.nifi.processor.email.extraction.EmailMessage other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.subject)) {
        this.subject = data().deepCopy(fields()[0].schema(), other.subject);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.body)) {
        this.body = data().deepCopy(fields()[1].schema(), other.body);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.body_type)) {
        this.body_type = data().deepCopy(fields()[2].schema(), other.body_type);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'subject' field.
      * @return The value.
      */
    public java.lang.CharSequence getSubject() {
      return subject;
    }

    /**
      * Sets the value of the 'subject' field.
      * @param value The value of 'subject'.
      * @return This builder.
      */
    public org.apache.nifi.processor.email.extraction.EmailMessage.Builder setSubject(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.subject = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'subject' field has been set.
      * @return True if the 'subject' field has been set, false otherwise.
      */
    public boolean hasSubject() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'subject' field.
      * @return This builder.
      */
    public org.apache.nifi.processor.email.extraction.EmailMessage.Builder clearSubject() {
      subject = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'body' field.
      * @return The value.
      */
    public java.lang.CharSequence getBody() {
      return body;
    }

    /**
      * Sets the value of the 'body' field.
      * @param value The value of 'body'.
      * @return This builder.
      */
    public org.apache.nifi.processor.email.extraction.EmailMessage.Builder setBody(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.body = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'body' field has been set.
      * @return True if the 'body' field has been set, false otherwise.
      */
    public boolean hasBody() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'body' field.
      * @return This builder.
      */
    public org.apache.nifi.processor.email.extraction.EmailMessage.Builder clearBody() {
      body = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'body_type' field.
      * @return The value.
      */
    public org.apache.nifi.processor.email.extraction.BodyType getBodyType() {
      return body_type;
    }

    /**
      * Sets the value of the 'body_type' field.
      * @param value The value of 'body_type'.
      * @return This builder.
      */
    public org.apache.nifi.processor.email.extraction.EmailMessage.Builder setBodyType(org.apache.nifi.processor.email.extraction.BodyType value) {
      validate(fields()[2], value);
      this.body_type = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'body_type' field has been set.
      * @return True if the 'body_type' field has been set, false otherwise.
      */
    public boolean hasBodyType() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'body_type' field.
      * @return This builder.
      */
    public org.apache.nifi.processor.email.extraction.EmailMessage.Builder clearBodyType() {
      body_type = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EmailMessage build() {
      try {
        EmailMessage record = new EmailMessage();
        record.subject = fieldSetFlags()[0] ? this.subject : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.body = fieldSetFlags()[1] ? this.body : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.body_type = fieldSetFlags()[2] ? this.body_type : (org.apache.nifi.processor.email.extraction.BodyType) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EmailMessage>
    WRITER$ = (org.apache.avro.io.DatumWriter<EmailMessage>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EmailMessage>
    READER$ = (org.apache.avro.io.DatumReader<EmailMessage>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
