/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.apache.nifi.processor.email.extraction;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class SenderDetails extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6905533363784843123L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SenderDetails\",\"namespace\":\"org.apache.nifi.processor.email.extraction\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"email_address\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SenderDetails> ENCODER =
      new BinaryMessageEncoder<SenderDetails>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SenderDetails> DECODER =
      new BinaryMessageDecoder<SenderDetails>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<SenderDetails> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<SenderDetails> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<SenderDetails>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this SenderDetails to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a SenderDetails from a ByteBuffer. */
  public static SenderDetails fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence name;
  @Deprecated public java.lang.CharSequence email_address;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SenderDetails() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param email_address The new value for email_address
   */
  public SenderDetails(java.lang.CharSequence name, java.lang.CharSequence email_address) {
    this.name = name;
    this.email_address = email_address;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return email_address;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: email_address = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'email_address' field.
   * @return The value of the 'email_address' field.
   */
  public java.lang.CharSequence getEmailAddress() {
    return email_address;
  }

  /**
   * Sets the value of the 'email_address' field.
   * @param value the value to set.
   */
  public void setEmailAddress(java.lang.CharSequence value) {
    this.email_address = value;
  }

  /**
   * Creates a new SenderDetails RecordBuilder.
   * @return A new SenderDetails RecordBuilder
   */
  public static org.apache.nifi.processor.email.extraction.SenderDetails.Builder newBuilder() {
    return new org.apache.nifi.processor.email.extraction.SenderDetails.Builder();
  }

  /**
   * Creates a new SenderDetails RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SenderDetails RecordBuilder
   */
  public static org.apache.nifi.processor.email.extraction.SenderDetails.Builder newBuilder(org.apache.nifi.processor.email.extraction.SenderDetails.Builder other) {
    return new org.apache.nifi.processor.email.extraction.SenderDetails.Builder(other);
  }

  /**
   * Creates a new SenderDetails RecordBuilder by copying an existing SenderDetails instance.
   * @param other The existing instance to copy.
   * @return A new SenderDetails RecordBuilder
   */
  public static org.apache.nifi.processor.email.extraction.SenderDetails.Builder newBuilder(org.apache.nifi.processor.email.extraction.SenderDetails other) {
    return new org.apache.nifi.processor.email.extraction.SenderDetails.Builder(other);
  }

  /**
   * RecordBuilder for SenderDetails instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SenderDetails>
    implements org.apache.avro.data.RecordBuilder<SenderDetails> {

    private java.lang.CharSequence name;
    private java.lang.CharSequence email_address;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.apache.nifi.processor.email.extraction.SenderDetails.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.email_address)) {
        this.email_address = data().deepCopy(fields()[1].schema(), other.email_address);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing SenderDetails instance
     * @param other The existing instance to copy.
     */
    private Builder(org.apache.nifi.processor.email.extraction.SenderDetails other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.email_address)) {
        this.email_address = data().deepCopy(fields()[1].schema(), other.email_address);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public org.apache.nifi.processor.email.extraction.SenderDetails.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public org.apache.nifi.processor.email.extraction.SenderDetails.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'email_address' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmailAddress() {
      return email_address;
    }

    /**
      * Sets the value of the 'email_address' field.
      * @param value The value of 'email_address'.
      * @return This builder.
      */
    public org.apache.nifi.processor.email.extraction.SenderDetails.Builder setEmailAddress(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.email_address = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'email_address' field has been set.
      * @return True if the 'email_address' field has been set, false otherwise.
      */
    public boolean hasEmailAddress() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'email_address' field.
      * @return This builder.
      */
    public org.apache.nifi.processor.email.extraction.SenderDetails.Builder clearEmailAddress() {
      email_address = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SenderDetails build() {
      try {
        SenderDetails record = new SenderDetails();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.email_address = fieldSetFlags()[1] ? this.email_address : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SenderDetails>
    WRITER$ = (org.apache.avro.io.DatumWriter<SenderDetails>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SenderDetails>
    READER$ = (org.apache.avro.io.DatumReader<SenderDetails>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
