/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Attachment extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2090222021543194924L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Attachment\",\"fields\":[{\"name\":\"data\",\"type\":\"bytes\"},{\"name\":\"file_name\",\"type\":\"string\"},{\"name\":\"mime_type\",\"type\":\"string\"},{\"name\":\"size\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Attachment> ENCODER =
      new BinaryMessageEncoder<Attachment>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Attachment> DECODER =
      new BinaryMessageDecoder<Attachment>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Attachment> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Attachment> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Attachment>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Attachment to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Attachment from a ByteBuffer. */
  public static Attachment fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.nio.ByteBuffer data;
  @Deprecated public java.lang.CharSequence file_name;
  @Deprecated public java.lang.CharSequence mime_type;
  @Deprecated public int size;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Attachment() {}

  /**
   * All-args constructor.
   * @param data The new value for data
   * @param file_name The new value for file_name
   * @param mime_type The new value for mime_type
   * @param size The new value for size
   */
  public Attachment(java.nio.ByteBuffer data, java.lang.CharSequence file_name, java.lang.CharSequence mime_type, java.lang.Integer size) {
    this.data = data;
    this.file_name = file_name;
    this.mime_type = mime_type;
    this.size = size;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return data;
    case 1: return file_name;
    case 2: return mime_type;
    case 3: return size;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: data = (java.nio.ByteBuffer)value$; break;
    case 1: file_name = (java.lang.CharSequence)value$; break;
    case 2: mime_type = (java.lang.CharSequence)value$; break;
    case 3: size = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'data' field.
   * @return The value of the 'data' field.
   */
  public java.nio.ByteBuffer getData() {
    return data;
  }

  /**
   * Sets the value of the 'data' field.
   * @param value the value to set.
   */
  public void setData(java.nio.ByteBuffer value) {
    this.data = value;
  }

  /**
   * Gets the value of the 'file_name' field.
   * @return The value of the 'file_name' field.
   */
  public java.lang.CharSequence getFileName() {
    return file_name;
  }

  /**
   * Sets the value of the 'file_name' field.
   * @param value the value to set.
   */
  public void setFileName(java.lang.CharSequence value) {
    this.file_name = value;
  }

  /**
   * Gets the value of the 'mime_type' field.
   * @return The value of the 'mime_type' field.
   */
  public java.lang.CharSequence getMimeType() {
    return mime_type;
  }

  /**
   * Sets the value of the 'mime_type' field.
   * @param value the value to set.
   */
  public void setMimeType(java.lang.CharSequence value) {
    this.mime_type = value;
  }

  /**
   * Gets the value of the 'size' field.
   * @return The value of the 'size' field.
   */
  public java.lang.Integer getSize() {
    return size;
  }

  /**
   * Sets the value of the 'size' field.
   * @param value the value to set.
   */
  public void setSize(java.lang.Integer value) {
    this.size = value;
  }

  /**
   * Creates a new Attachment RecordBuilder.
   * @return A new Attachment RecordBuilder
   */
  public static Attachment.Builder newBuilder() {
    return new Attachment.Builder();
  }

  /**
   * Creates a new Attachment RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Attachment RecordBuilder
   */
  public static Attachment.Builder newBuilder(Attachment.Builder other) {
    return new Attachment.Builder(other);
  }

  /**
   * Creates a new Attachment RecordBuilder by copying an existing Attachment instance.
   * @param other The existing instance to copy.
   * @return A new Attachment RecordBuilder
   */
  public static Attachment.Builder newBuilder(Attachment other) {
    return new Attachment.Builder(other);
  }

  /**
   * RecordBuilder for Attachment instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Attachment>
    implements org.apache.avro.data.RecordBuilder<Attachment> {

    private java.nio.ByteBuffer data;
    private java.lang.CharSequence file_name;
    private java.lang.CharSequence mime_type;
    private int size;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Attachment.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.data)) {
        this.data = data().deepCopy(fields()[0].schema(), other.data);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.file_name)) {
        this.file_name = data().deepCopy(fields()[1].schema(), other.file_name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.mime_type)) {
        this.mime_type = data().deepCopy(fields()[2].schema(), other.mime_type);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.size)) {
        this.size = data().deepCopy(fields()[3].schema(), other.size);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Attachment instance
     * @param other The existing instance to copy.
     */
    private Builder(Attachment other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.data)) {
        this.data = data().deepCopy(fields()[0].schema(), other.data);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.file_name)) {
        this.file_name = data().deepCopy(fields()[1].schema(), other.file_name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.mime_type)) {
        this.mime_type = data().deepCopy(fields()[2].schema(), other.mime_type);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.size)) {
        this.size = data().deepCopy(fields()[3].schema(), other.size);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'data' field.
      * @return The value.
      */
    public java.nio.ByteBuffer getData() {
      return data;
    }

    /**
      * Sets the value of the 'data' field.
      * @param value The value of 'data'.
      * @return This builder.
      */
    public Attachment.Builder setData(java.nio.ByteBuffer value) {
      validate(fields()[0], value);
      this.data = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'data' field has been set.
      * @return True if the 'data' field has been set, false otherwise.
      */
    public boolean hasData() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'data' field.
      * @return This builder.
      */
    public Attachment.Builder clearData() {
      data = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'file_name' field.
      * @return The value.
      */
    public java.lang.CharSequence getFileName() {
      return file_name;
    }

    /**
      * Sets the value of the 'file_name' field.
      * @param value The value of 'file_name'.
      * @return This builder.
      */
    public Attachment.Builder setFileName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.file_name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'file_name' field has been set.
      * @return True if the 'file_name' field has been set, false otherwise.
      */
    public boolean hasFileName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'file_name' field.
      * @return This builder.
      */
    public Attachment.Builder clearFileName() {
      file_name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'mime_type' field.
      * @return The value.
      */
    public java.lang.CharSequence getMimeType() {
      return mime_type;
    }

    /**
      * Sets the value of the 'mime_type' field.
      * @param value The value of 'mime_type'.
      * @return This builder.
      */
    public Attachment.Builder setMimeType(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.mime_type = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'mime_type' field has been set.
      * @return True if the 'mime_type' field has been set, false otherwise.
      */
    public boolean hasMimeType() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'mime_type' field.
      * @return This builder.
      */
    public Attachment.Builder clearMimeType() {
      mime_type = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'size' field.
      * @return The value.
      */
    public java.lang.Integer getSize() {
      return size;
    }

    /**
      * Sets the value of the 'size' field.
      * @param value The value of 'size'.
      * @return This builder.
      */
    public Attachment.Builder setSize(int value) {
      validate(fields()[3], value);
      this.size = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'size' field has been set.
      * @return True if the 'size' field has been set, false otherwise.
      */
    public boolean hasSize() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'size' field.
      * @return This builder.
      */
    public Attachment.Builder clearSize() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Attachment build() {
      try {
        Attachment record = new Attachment();
        record.data = fieldSetFlags()[0] ? this.data : (java.nio.ByteBuffer) defaultValue(fields()[0]);
        record.file_name = fieldSetFlags()[1] ? this.file_name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.mime_type = fieldSetFlags()[2] ? this.mime_type : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.size = fieldSetFlags()[3] ? this.size : (java.lang.Integer) defaultValue(fields()[3]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Attachment>
    WRITER$ = (org.apache.avro.io.DatumWriter<Attachment>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Attachment>
    READER$ = (org.apache.avro.io.DatumReader<Attachment>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
